//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WinDjView.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_PRINT                       101
#define IDD_PROGRESS                    102
#define IDD_ZOOM                        103
#define IDD_GOTO_PAGE                   104
#define IDD_UPDATE                      105
#define IDD_FIND                        106
#define IDD_SETTINGS                    107
#define IDD_SETTINGS_GENERAL            108
#define IDD_SETTINGS_DISPLAY            109
#define IDD_SETTINGS_ADVANCED           110
#define IDD_ANNOTATION                  111
#define IDD_RENAME_BOOKMARK             112
#define IDD_INSTALL_DIC                 113
#define IDD_INSTALL_DIC_REPLACE         114
#define IDD_SETTINGS_DICT               115
#define IDD_DOC_PROPERTIES              116
#define IDR_MAINFRAME                   128
#define IDR_DjVuTYPE                    129
#define IDR_POPUP                       130
#define IDC_CURSOR_HAND                 131
#define IDC_CURSOR_DRAG                 132
#define IDC_CURSOR_LINK                 133
#define IDC_CURSOR_MAGNIFY              134
#define IDC_CURSOR_PAN_UR               135
#define IDC_CURSOR_PAN_ALL              136
#define IDC_CURSOR_PAN_D                137
#define IDC_CURSOR_PAN_DL               138
#define IDC_CURSOR_PAN_DR               139
#define IDC_CURSOR_PAN_L                140
#define IDC_CURSOR_PAN_LR               141
#define IDC_CURSOR_PAN_R                142
#define IDC_CURSOR_PAN_U                143
#define IDC_CURSOR_PAN_UD               144
#define IDC_CURSOR_PAN_UL               145
#define IDB_PAN_ANCHOR                  146
#define IDB_HOURGLASS                   147
#define IDB_CLOSE                       148
#define IDB_BOOKMARKS                   149
#define IDB_DONATE                      150
#define IDC_CURSOR_ZOOM_RECT            151
#define IDC_CURSOR_SPLIT_HORZ           152
#define IDB_SETTINGS                    153
#define IDB_CLOSE_TAB                   154
#define IDR_DICT_BAR                    155
#define IDR_DICT_BAR_GRAYED             156
#define IDR_TOOLBAR_GRAYED              157
#define IDS_CONTENTS_TAB                200
#define IDS_MAKE_DEFAULT_FAILED         202
#define IDS_PAGE_INDEX_TAB              203
#define IDS_THUMBNAILS_TAB              204
#define IDS_SEARCH_RESULTS_TAB          205
#define IDS_SAVE_COPY_AS                206
#define IDS_DJVU_FILTER                 207
#define IDS_CANNOT_SAVE_TO_ORIG         208
#define IDS_SAVE_ERROR                  209
#define IDS_ERROR_DECODING_PAGE         210
#define IDS_BMP_FILTER                  211
#define IDS_EXPORT_PAGE                 212
#define IDS_CONNECT_ERROR               213
#define IDS_NO_UPDATES_AVAILABLE        214
#define IDS_NEW_VERSION_AVAILABLE       215
#define IDS_VERSION_URL                 216
#define IDS_WEBSITE_URL                 217
#define IDS_DJVULIBRE_URL               218
#define IDS_DONATE_URL                  219
#define IDS_STRING_NOT_FOUND            220
#define IDS_PRINTING                    221
#define IDS_ERROR_RENDERING_PAGE        222
#define IDS_SEARCHING_PAGE              223
#define IDS_NUM_OCCURRENCES             224
#define IDS_EXPORT_TEXT                 225
#define IDS_TEXT_FILTER                 226
#define IDS_PRINTING_PAGE               227
#define IDS_SEARCHING                   228
#define IDS_OF_PAGE_COUNT               229
#define IDS_FIT_WIDTH                   230
#define IDS_FIT_HEIGHT                  231
#define IDS_FIT_PAGE                    232
#define IDS_ACTUAL_SIZE                 233
#define IDS_STRETCH                     234
#define IDS_TOOLTIP_BRIGHTNESS          235
#define IDS_TOOLTIP_CONTRAST            236
#define IDS_TOOLTIP_GAMMA               237
#define IDS_STATUS_BLACKANDWHITE        238
#define IDS_STATUS_FOREGROUND           239
#define IDS_STATUS_BACKGROUND           240
#define IDS_PRINT_ALL_PAGES             241
#define IDS_PRINT_ODD_PAGES             242
#define IDS_PRINT_EVEN_PAGES            243
#define IDS_PRINT_ONE_PAGE              244
#define IDS_PRINT_TWO_PAGES             245
#define IDS_PLEASE_WAIT                 246
#define IDS_PAGE_NO_TOOLTIP             247
#define IDS_BRIGHTNESS_TEXT_ZERO        248
#define IDS_BRIGHTNESS_TEXT             249
#define IDS_CONTRAST_TEXT_ZERO          250
#define IDS_CONTRAST_TEXT               251
#define IDS_GAMMA_TEXT                  252
#define IDS_FAILED_TO_OPEN              253
#define IDS_TOOLBAR_TITLE               254
#define IDS_TOOLTIP_HIDE                255
#define IDS_NOT_VALID_DOCUMENT          256
#define IDS_PRINTING_FAILED             257
#define IDS_PAPER_SIZE                  258
#define IDS_VERSION_INFO                259
#define IDS_VERSION_ABOUT               260
#define IDS_CURRENT_VERSION             261
#define IDS_FATAL_ERROR                 262
#define IDS_WARN_CLOSE_MULTIPLE         263
#define IDS_OPENFILE                    264
#define IDS_ALLFILTER                   265
#define IDS_SETTINGS                    266
#define IDS_BORDER_TYPES                267
#define IDS_FILL_TYPES                  268
#define IDS_COLOR_PALETTE               269
#define IDS_MORE_COLORS                 270
#define IDS_BOOKMARKS_TAB               271
#define IDS_BOOKMARK_MORE               272
#define IDS_BOOKMARK_LESS               273
#define IDS_UNITS_FULL                  274
#define IDS_UNITS_SHORT                 275
#define IDS_EDIT_ANNOTATION             276
#define IDS_CREATE_ANNOTATION           277
#define IDS_BOOKMARK_SELECTION          278
#define IDS_BOOKMARK_ANNOTATION         279
#define IDS_BOOKMARK_VIEW               280
#define IDS_RENAME_BOOKMARK             281
#define IDS_PROMPT_BOOKMARK_DESTINATION 282
#define IDS_PROMPT_BOOKMARK_DELETE      283
#define IDS_PROMPT_ANNOTATION_DELETE    284
#define IDS_FILE_INSTALL                285
#define IDS_INSTALLATION_FAILED         286
#define IDS_INSTALLATION_SUCCEEDED      287
#define IDS_ERROR_PARSING_RANGE         288
#define IDS_PATH_TOO_LONG               289
#define IDS_DICTBAR_TITLE               290
#define IDS_LANG_NOT_SPECIFIED          291
#define IDS_UNINSTALL_DICT              292
#define IDS_UNINSTALL_FAILED            293
#define IDS_PRINT_BOOKLET               294
#define IDS_DICT_LOCATION_PROMPT        295
#define IDS_INVALID_DIR                 296
#define IDS_COPY_SELECTION              297
#define IDS_RESTART_NEEDED              298
#define IDS_TOOLTIP_SETTINGS            299
#define IDS_CLOSE_TAB                   300
#define IDS_DOC_TYPES                   301
#define IDS_FILE_TYPES                  302
#define IDS_DOC_FILES_COLUMNS           303
#define IDS_BOOKMARKS_FILTER            304
#define IDS_EXPORT_BOOKMARKS            305
#define IDS_IMPORT_BOOKMARKS            306
#define IDS_CANNOT_OPEN_BOOKMARKS       307
#define IDS_CANNOT_READ_BOOKMARKS       308
#define IDS_BOOKMARKS_EMPTY             309
#define IDS_BOOKMARKS_PROMPT            310
#define IDS_BOOKMARKS_PROMPT_CAPTIONS   311
#define IDS_SEARCH_WRAPPED              312
#define IDS_BOOKMARK_TOP_LEVEL          313
#define IDS_PROMPT_MAKE_DEFAULT_VIEWER  314
#define IDS_WARN_NOT_DEFAULT_VIEWER     315
#define IDS_DEFAULT_VIEWER              316
#define IDS_NOT_DEFAULT_VIEWER          317
#define IDS_TAB_BAR_MENU                318
#define IDS_CHECK_CLOSE_MULTIPLE        319
#define IDS_CANNOT_WRITE_TO_FILE        320
#define IDS_REGISTRY_FILTER             321
#define IDS_BACKUP_BOOKMARKS            322
#define IDS_CHECK_UPDATES               323
#define IDS_ABOUT_LICENSE               324
#define IDS_IMAGE_FILTER                325
#define IDS_ERROR_EXPORTING_PAGE        326
#define IDS_EXPORT_PROMPT_OVERWRITE     327
#define IDS_EXPORTING_PAGE              328
#define IDS_EXPORT_PAGES                329
#define IDS_EXPORT_ERRORS               330
#define IDC_COMBO_PRINTER               1000
#define IDC_COMBO_PAPER                 1001
#define IDC_PRINT_TO_FILE               1002
#define IDC_RANGE_ALL                   1003
#define IDC_RANGE_CURRENT               1004
#define IDC_RANGE_SELECTION             1005
#define IDC_RANGE_PAGES                 1006
#define IDC_PAGE_RANGES                 1007
#define IDC_SPIN_COPIES                 1008
#define IDC_EDIT_COPIES                 1009
#define IDC_COLLATE                     1010
#define IDC_STATIC_TYPE                 1011
#define IDC_STATIC_LOCATION             1012
#define IDC_STATIC_COMMENT              1013
#define IDC_PORTRAIT                    1014
#define IDC_LANDSCAPE                   1015
#define IDC_COMBO_PAGESINRANGE          1016
#define IDC_MARGIN_LEFT                 1017
#define IDC_MARGIN_TOP                  1018
#define IDC_MARGIN_RIGHT                1019
#define IDC_MARGIN_BOTTOM               1020
#define IDC_PREVIEW_AREA                1021
#define IDC_COMBO_PAGESPERSHEET         1022
#define IDC_POSITION_LEFT               1023
#define IDC_POSITION_TOP                1024
#define IDC_SCALE                       1025
#define IDC_CENTER_IMAGE                1026
#define IDC_SCALE_TO_FIT                1027
#define IDC_SHRINK_OVERSIZED            1028
#define IDC_STATIC_PAPER                1029
#define IDC_CLIP_CONTENT                1030
#define IDC_PROGRESS                    1031
#define IDC_AUTO_ROTATE                 1032
#define IDC_IGNORE_MARGINS              1033
#define IDC_STATIC_TEXT                 1034
#define IDC_REVERSE                     1035
#define IDC_WARN_NOT_DEFAULT_VIEWER     1036
#define IDC_MATCH_CASE                  1037
#define IDC_GEN_ALL_THUMBNAILS          1038
#define IDC_STATIC_LINK                 1039
#define IDC_RESTORE_TABS                1040
#define IDC_STATIC_LIB_LINK             1041
#define IDC_FULLSCREEN_HIDESCROLL       1042
#define IDC_MAKE_DEFAULT                1043
#define IDC_TOP_LEVEL_DOCUMENTS         1044
#define IDC_FULLSCREEN_CLICKS           1045
#define IDC_STATIC_ABOUT                1046
#define IDC_FULLSCREEN_CONTINUOUS       1047
#define IDC_FIND                        1048
#define IDC_INVERT_WHEEL_ZOOM           1049
#define IDC_HQ_COLOR_SCALING            1050
#define IDC_ADJUST_DISPLAY              1051
#define IDC_BRIGHTNESS                  1052
#define IDC_CONTRAST                    1053
#define IDC_GAMMA                       1054
#define IDC_BRIGHTNESS_TEXT             1055
#define IDC_CONTRAST_TEXT               1056
#define IDC_GAMMA_TEXT                  1057
#define IDC_SEARCH_STATUS               1058
#define IDC_INVERT_COLORS               1059
#define IDC_PAGE                        1060
#define IDC_CLOSE_ON_ESC                1061
#define IDC_ADJUST_PRINTING             1062
#define IDC_PAGE_COUNT                  1063
#define IDC_WRAP_BOOKMARKS              1064
#define IDC_RESTORE_VIEW                1065
#define IDC_DONATE                      1066
#define IDC_STATIC_VERSION              1067
#define IDC_SPIN_PAGE                   1068
#define IDC_BORDER_TYPE                 1069
#define IDC_FILL_TYPE                   1070
#define IDC_HIDE_INACTIVE_BORDER        1071
#define IDC_FILL_TRANSPARENCY           1072
#define IDC_FILL_TRANSPARENCY_TEXT      1073
#define IDC_BORDER_COLOR                1074
#define IDC_FILL_COLOR                  1075
#define IDC_HIDE_INACTIVE_FILL          1076
#define IDC_ALWAYS_SHOW_COMMENT         1077
#define IDC_COMMENT                     1078
#define IDC_PAGENUM                     1079
#define IDC_BOOKMARK_TITLE              1080
#define IDC_ZOOM                        1081
#define IDC_STATIC_LESS                 1082
#define IDC_STATIC_MORE                 1083
#define IDC_ADD_BOOKMARK                1084
#define IDC_COMBO_UNITS                 1085
#define IDC_CURRENT_USER                1086
#define IDC_ALL_USERS                   1087
#define IDC_KEEP_ORIGINAL               1088
#define IDC_LOOKUP                      1089
#define IDC_CUSTOM                      1090
#define IDC_LOOKUP_LABEL                1091
#define IDC_DICTIONARY                  1092
#define IDC_DICTIONARY_LABEL            1093
#define IDC_LIST                        1094
#define IDC_LANGUAGE_LIST               1095
#define IDC_LANGUAGE_LIST_LABEL         1096
#define IDC_UNINSTALL                   1097
#define IDC_CUSTOM_LOCATION             1098
#define IDC_BROWSE_LOCATION             1099
#define IDC_STATIC_NAME                 1100
#define IDC_STATIC_SIZE                 1101
#define IDC_STATIC_PAGES                1102
#define IDC_STATIC_FILES                1103
#define IDC_LIST_FILES                  1104
#define IDC_SHOW_ALL_FILES              1105
#define IDC_HIDE_SINGLE_TAB             1106
#define IDC_DEFAULT_VIEWER_STATUS       1107
#define IDC_STATIC_LICENSE              1108
#define IDC_SUBPIXEL_SCALING            1109
#define IDC_CREATE_BACKUP               1110
#define IDC_CHECK_UPDATES               1111
#define IDC_PROPERTIES                  1112
#define IDC_FIND_ALL                    1113
#define ID_VIEW_NEXTPAGE                32771
#define ID_VIEW_PREVIOUSPAGE            32772
#define ID_VIEW_NEXTPAGE_SHORTCUT       32773
#define ID_VIEW_PREVIOUSPAGE_SHORTCUT   32774
#define ID_ZOOM_50                      32775
#define ID_ZOOM_75                      32776
#define ID_ZOOM_100                     32777
#define ID_ZOOM_200                     32778
#define ID_ZOOM_400                     32779
#define ID_ZOOM_FITWIDTH                32780
#define ID_ZOOM_FITHEIGHT               32781
#define ID_ZOOM_FITPAGE                 32782
#define ID_ZOOM_ACTUALSIZE              32783
#define ID_ZOOM_STRETCH                 32784
#define ID_ZOOM_CUSTOM                  32785
#define ID_BOOKMARK_TOP_LEVEL           32786
#define ID_ROTATE_LEFT                  32787
#define ID_ROTATE_RIGHT                 32788
#define ID_ROTATE_180                   32789
#define ID_VIEW_FIRSTPAGE               32790
#define ID_VIEW_LASTPAGE                32791
#define ID_VIEW_FIRSTPAGE_SHORTCUT      32792
#define ID_VIEW_LASTPAGE_SHORTCUT       32793
#define ID_PAGE_INFORMATION             32794
#define ID_VIEW_LAYOUT                  32795
#define ID_FILE_SETTINGS                32796
#define ID_EXPORT_PAGE                  32797
#define ID_EXPORT_SELECTION             32798
#define ID_VIEW_BACK                    32799
#define ID_VIEW_BACK_SHORTCUT           32800
#define ID_VIEW_FORWARD                 32801
#define ID_VIEW_FORWARD_SHORTCUT        32802
#define ID_WINDOW_ACTIVATE_FIRST        32803
#define ID_WINDOW_ACTIVATE_1            32804
#define ID_WINDOW_ACTIVATE_2            32805
#define ID_WINDOW_ACTIVATE_3            32806
#define ID_WINDOW_ACTIVATE_4            32807
#define ID_WINDOW_ACTIVATE_5            32808
#define ID_WINDOW_ACTIVATE_6            32809
#define ID_WINDOW_ACTIVATE_7            32810
#define ID_WINDOW_ACTIVATE_8            32811
#define ID_WINDOW_ACTIVATE_9            32812
#define ID_WINDOW_ACTIVATE_10           32813
#define ID_WINDOW_ACTIVATE_11           32814
#define ID_WINDOW_ACTIVATE_12           32815
#define ID_WINDOW_ACTIVATE_13           32816
#define ID_WINDOW_ACTIVATE_14           32817
#define ID_WINDOW_ACTIVATE_LAST         32818
#define ID_ZOOM_IN                      32819
#define ID_ZOOM_OUT                     32820
#define ID_MODE_DRAG                    32821
#define ID_MODE_SELECT                  32822
#define ID_MODE_MAGNIFY                 32823
#define ID_MODE_SELECT_RECT             32824
#define ID_MODE_ZOOM_RECT               32825
#define ID_FILE_EXPORT_TEXT             32826
#define ID_CHECK_FOR_UPDATE             32827
#define ID_DISPLAY_COLOR                32828
#define ID_DISPLAY_BW                   32829
#define ID_DISPLAY_BACKGROUND           32830
#define ID_DISPLAY_FOREGROUND           32831
#define ID_VIEW_FULLSCREEN              32832
#define ID_VIEW_GOTO_PAGE               32833
#define ID_LANGUAGE_FIRST               32834
#define ID_LANGUAGE_LAST                33089
#define ID_LAYOUT_CONTINUOUS            33091
#define ID_LAYOUT_FACING                33092
#define ID_LAYOUT_FIRSTPAGE_ALONE       33094
#define ID_HIGHLIGHT_SELECTION          33095
#define ID_HIGHLIGHT_TEXT               33096
#define ID_ANNOTATION_EDIT              33097
#define ID_ANNOTATION_DELETE            33098
#define ID_FIND_STRING                  33099
#define ID_INDICATOR_PAGE               33100
#define ID_INDICATOR_SIZE               33101
#define ID_INDICATOR_ADJUST             33102
#define ID_INDICATOR_MODE               33103
#define ID_FIND_ALL                     33104
#define ID_BOOKMARK_DELETE              33105
#define ID_BOOKMARK_RENAME              33106
#define ID_BOOKMARK_SETDESTINATION      33107
#define ID_BOOKMARK_ADD                 33108
#define ID_ZOOM_TO_SELECTION            33109
#define ID_VIEW_SIDEBAR                 33110
#define ID_FILE_INSTALL                 33111
#define ID_DICTIONARY_NEXT              33112
#define ID_DICTIONARY_PREV              33113
#define ID_DICTIONARY_INFO              33114
#define ID_DICTIONARY_LOOKUP            33115
#define ID_VIEW_DICTBAR                 33116
#define ID_FOCUS_TO_LOOKUP              33117
#define ID_BOOKMARK_MOVEUP              33118
#define ID_BOOKMARK_MOVEDOWN            33119
#define ID_THUMBNAILS_ENLARGE           33120
#define ID_THUMBNAILS_REDUCE            33121
#define ID_BOOKMARK_WRAP                33122
#define ID_TAB_CLOSE                    33123
#define ID_TAB_CLOSE_OTHER              33124
#define ID_WINDOW_NEXT                  33125
#define ID_WINDOW_PREV                  33126
#define ID_LAYOUT_RTL_ORDER             33127
#define ID_FILE_DOC_PROPERTIES          33128
#define ID_FILE_IMPORT_BOOKMARKS        33129
#define ID_FILE_EXPORT_BOOKMARKS        33130
#define ID_VIEW_TAB_BAR                 33131
#define ID_TOGGLE_NAV_PANE              33132
#define ID_THUMBNAILS_PRINT             33133
#define ID_THUMBNAILS_EXPORT            33134

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        331
#define _APS_NEXT_COMMAND_VALUE         33135
#define _APS_NEXT_CONTROL_VALUE         1114
#define _APS_NEXT_SYMED_VALUE           117
#endif
#endif
